name: Semantic-release
on:
  push:
    branches: [ main, alpha ]
  pull_request:
    branches: [ main, alpha ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npx semantic-release